# Horizon 52 - nice!nano v2

# USB + Bluetooth
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Bluetooth name
CONFIG_BT_DEVICE_NAME="Horizon 52"

# Five Bluetooth host profiles

# Power management
CONFIG_ZMK_SLEEP=y
